version: "3.9"

networks:
  internet:
    driver: bridge
  reverse-proxy:
    external: true
    
services:
  main:
    image: searxng/searxng:2026.7.10-4abac08de
    volumes:
      - ./settings.yml:/etc/searxng/settings.yml:ro
    networks:
      - internet
      - reverse-proxy
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      - BASE_URL=https://search.actuary.dev
      - INSTANCE_NAME=search
      - SEARXNG_SECRET=${SEARXNG_SECRET_KEY}
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.search.rule=Host(`search.actuary.dev`)"
        - "traefik.http.routers.search.entrypoints=websecure"
        - "traefik.http.routers.search.service=search"
        - "traefik.http.routers.search.tls.certresolver=myresolver"
        - "traefik.http.services.search.loadbalancer.server.port=8080"
        ## Middlewares
        - "traefik.http.routers.search.middlewares=authentik@swarm"
        #DIUN
        - diun.enable=true
        - diun.notify_on=new
