name: 'deploy'
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  traefik:
    runs-on: [coral]
    env:
      TAG: ${{ github.sha }}
      SEARXNG_SECRET_KEY: ${{ secrets.SEARXNG_SECRET_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          repository: Actuary-LLC/searxng
          ref: main
      - name: Cleanup orphaned networks
        run: |
          docker network rm searxng_internet 2>/dev/null || true
      - name: Update searxng stack
        run: |
          docker stack deploy -c searxng.yaml searxng
